import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect, useRef, useCallback } from "react";
import xlsx from "xlsx";
export default function Home() {
  const [file, setFile] = useState(null);
  const workerRef = useRef();
  useEffect(() => {
    workerRef.current = new Worker(
      new URL("@workers/test.worker.js", import.meta.url)
    );
    workerRef.current.onmessage = (e) => {
      console.log(e.data);
    };
    return () => workerRef.current.terminate();
  }, []);
  const handleWork = useCallback(async () => {
    workerRef.current.postMessage({ n1: 2, n2: 3 });
  }, []);
  useEffect(() => {
    console.log({ file });
  }, [file]);
  const readUploadFile = (e) => {
    e.preventDefault();

    if (e.target.files || e.dataTransfer.files.length) {
      const reader = new FileReader();
      reader.onload = (e) => {
        const data = e.target.result;
        const workbook = xlsx.read(data, { type: "array" });
        const sheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[sheetName];
        const headers = xlsx.utils.sheet_to_json(worksheet, { header: 1 })[0];
        const json = xlsx.utils.sheet_to_json(worksheet);
        workerRef.current.postMessage({ headers, json });
      };
      reader.readAsArrayBuffer(
        e?.target?.files?.[0] || e?.dataTransfer?.files?.[0]
      );
    }
  };

  return (
    <div
      className={styles.container}
      onDrop={readUploadFile}
      onDragOver={(e) => e.preventDefault()}
      style={{ height: "100vh", background: "blue" }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handleWork}>work</button>
      Holi
      <input type="file" onChange={readUploadFile} />
      <footer className={styles.footer}></footer>
    </div>
  );
}
